### ISSUE TITLE
训练过久Loss变为Nan

### ISSUE THREAD

**Issue by 1359347500cwc** [workforai/GSFM#1]
你好，我非常欣赏你的工作，但是当我对你的工作进行复现实验的时候出现了以下问题，希望你能帮我解决。
参数配置：
RTX3090;
torch 1.11.0;
stage3参数改动（因为是单卡，所以将iterations延长）
![image](https://user-images.githubusercontent.com/57097883/201591747-72bd7c06-9666-455d-a71f-044730a46d5c.png)

在加载模型时由于torch版本问题
torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnXgeqrf( handle, params, m, n, CUDA_R_32F, reinterpret_cast<void*>(A), lda, CUDA_R_32F, reinterpret_cast<void*>(tau), CUDA_R_32F, reinterpret_cast<void*>(bufferOnDevice), workspaceInBytesOnDevice, reinterpret_cast<void*>(bufferOnHost), workspaceInBytesOnHost, info)`. This error may appear if the input matrix contains NaN.
对代码进行改动为
![image](https://user-images.githubusercontent.com/57097883/201591452-c3425890-9161-4fa5-a498-49beef790755.png)
将矩阵的正交初始化移到cpu上计算然后上传到gpu上，其他没有改动。

stage3训练时刚开始的loss下降正常，但是iteration迭代次数过多时所有的Loss均将为Nan,并且将10000iteration的权重进行推理时，且没有分割结果。

**Comment by yongliu20** [comment]
你用单卡训练相当于总的batchsize变为了1/8，lr也要对应改变的。你用原来的loss太大了

**Comment by 1359347500cwc** [comment]
好的，感谢！！
