### ISSUE TITLE
UserWarning: Casting complex values to real discards the imaginary part 请问这个警告会有影响吗，傅里叶逆变换的时候出现的

### ISSUE THREAD

**Issue by lzl2040** [workforai/GSFM#2]

**Comment by yongliu20** [comment]
请问这个warning总是出现吗？我跑了一下0阶段和3阶段的几个epoch好像没有发现这个warning。如果是偶尔某个iteration出现应该没有什么影响

**Comment by lzl2040** [comment]
> 请问这个warning总是出现吗？我跑了一下0阶段和3阶段的几个epoch好像没有发现这个warning。如果是偶尔某个iteration出现应该没有什么影响

是在训练的最开始出现的，之后都没有了

**Comment by yongliu20** [comment]
我观察到了，这个不影响的
