### ISSUE TITLE
将LFM用于STM当中时，LFM模块的输入是什么呢？memory encoder和query encoder都使用了LFM吗

### ISSUE THREAD

**Issue by lzl2040** [workforai/GSFM#3]

**Comment by yongliu20** [comment]
Yes, both memory and query use LFM. The code and Fig.2 in the paper show this clearly.

**Comment by lzl2040** [comment]
> Yes, both memory and query use LFM. The code and Fig.2 in the paper show this clearly.

但是STM中的memory encoder是以image和mask为输入的（跟本文不一样，本文是以image为输入的）。那在STM中是先经过memory encoder然后再通过LFM最后才映射到key space和value space吗

**Comment by yongliu20** [comment]
Yes.

**Comment by lzl2040** [comment]
> Yes.

ok,thank you
