### ISSUE TITLE
How to make such an Illustration shown in Fig 1 of your paper?

### ISSUE THREAD

**Issue by jhl-Det** [workforai/GSFM#4]
Hi there, 
I am reading your paper recently, the core-designed module LFM really sheds some light on this field!
And I am also interested in your analysis of the problem, especially the way you compare your GSFM with other SOTA, as shown in figure 1. 
Could you teach me how to make such an Illustration? How to find the matched pixels according to the query pixel?
Best Regard!!!

**Comment by yongliu20** [comment]
Thanks for your recognition of our work! The matched pixels are obtained from the similarity map of the memory key and query key. Given the coordinates of a point in the query, we can get the similarity magnitude of all points in memory with it. Finally, the similarity map is converted into a heat map and added to the original image.
